Repository TheHive-Project/TheHive4py, pull requests merged in 2020-11, with the labels that each got.

#187 Added MISP export functionality
  thehive4py/api.py
Labels: feature request

#181 Adding externalLink to Alert model
  thehive4py/models.py
Labels: TheHive 4, feature request

#164 Merge alert to case
  thehive4py/api.py
Labels: feature request

#202 Add method to delete alert
  thehive4py/api.py
Labels: category:feature-request

#199 Fixed typo in explanation part of some functions in query.py
  thehive4py/query.py
Labels: scope:docs

#203 Fix exception handling for merge_alert_into_case
  thehive4py/api.py
Labels: category:bug

#135 Pass in file-like objects for case observables
  tests/test_files.py
  thehive4py/models.py
Labels: category:feature-request
