Repository TheHive-Project/TheHive4py, pull requests merged in 2023-01, with the labels that each got.

#265 Create local ci commands for devs
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  README.md
  pyproject.toml
  scripts/cd.py
  scripts/ci.py
Labels: 2.x

#269 Add parameters to method alert.promote_to_case()
  tests/test_alert_endpoint.py
  thehive4py/endpoints/alert.py
  thehive4py/types/alert.py
Labels: category:enhancement, target:2.x

#266 Download an attachment from an observable
  thehive4py/endpoints/observable.py
Labels: 2.x

#271 268 add case and alert ttps operations
  tests/test_alert_endpoint.py
  tests/test_case_endpoint.py
  thehive4py/endpoints/alert.py
  thehive4py/endpoints/case.py
  thehive4py/endpoints/procedure.py
  thehive4py/types/procedure.py
Labels: category:feature-request, 2.x

#270 Test observable attachment download
  tests/test_observable_endpoint.py
  tests/utils.py
  thehive4py/endpoints/_base.py
  thehive4py/endpoints/observable.py
Labels: 2.x

#272 add py.typed to the project to please mypy and make the library PEP-561 compliant
  pyproject.toml
  thehive4py/py.typed
Labels: category:enhancement, 2.x
