Repository TheHive-Project/TheHive4py, pull requests merged in 2025-05, with the labels that each got.

#415 #414 - Use TheHive v5.4.9 in integration tests
  tests/conftest.py
Labels: 2.x

#412 #410 - Review and fix alert docs
  docs/examples/alert.md
  examples/alert/fetch_with_find.py
  examples/alert/observable_from_file.py
  thehive4py/endpoints/alert.py
Labels: 2.x

#413 #411 - Fix changelog linkification script
  docs/release-notes.md
  scripts/linkify_release_notes.py
Labels: 2.x

#418 #417 - consider empty dicts in json requests
  tests/test_alert_endpoint.py
  thehive4py/session.py
Labels: 2.x, changelog:fixed

#421 #419 - Use TheHive v5.5.1 in integration tests
  tests/conftest.py
Labels: 2.x

#422 #411 - Remove quickfix functions
  scripts/linkify_release_notes.py
Labels: 2.x, changelog:ignore

#424 #423 - Release v2.0.0b10
  docs/release-notes.md
  pyproject.toml
Labels: 2.x, changelog:ignore

#430 #428 - Update OutputObservableRequired type
  thehive4py/types/observable.py
Labels: 2.x, changelog:changed

#432 #302 - Review organisation endpoint methods and types
  tests/test_organisation_endpoint.py
  tests/utils.py
  thehive4py/endpoints/organisation.py
  thehive4py/types/organisation.py
Labels: 2.x, changelog:added, changelog:changed, changelog:fixed

#439 #434 - Review alert endpoints
  tests/test_alert_endpoint.py
  thehive4py/endpoints/alert.py
Labels: 2.x, changelog:added, changelog:changed, changelog:deprecated

#450 #435 - Review case endpoints
  tests/test_case_endpoint.py
  thehive4py/endpoints/case.py
  thehive4py/types/case.py
  thehive4py/types/custom_field.py
Labels: 2.x, changelog:added, changelog:changed, changelog:deprecated

#451 #438 - Review task log endpoints
  tests/test_task_log_endpoint.py
  thehive4py/endpoints/task_log.py
  thehive4py/types/task_log.py
Labels: 2.x
