Repository TheHive-Project/TheHive4py, pull requests merged in 2025-01, with the labels that each got.

#379 #362 - Add release.yml
  .github/release.yml
Labels: 2.x, changelog:added

#383 #380 - Update case and alert types
  thehive4py/types/alert.py
  thehive4py/types/case.py
Labels: 2.x, changelog:changed

#382 #381 - Use TheHive 5.4.6 in integration tests
  tests/conftest.py
Labels: 2.x, changelog:changed

#377 Fix deprecations, add warning for Contains
  tests/test_query_filters.py
  thehive4py/query/__init__.py
  thehive4py/query/filters.py
Labels: 2.x, changelog:added, changelog:changed

#384 #361 - Add deprecation warning for python 3.8
  tests/test_init.py
  thehive4py/__init__.py
Labels: 2.x, changelog:deprecated

#375 Case template endpoint
  .pre-commit-config.yaml
  tests/conftest.py
  tests/test_case_template_endpoint.py
  tests/utils.py
  thehive4py/client.py
  thehive4py/endpoints/__init__.py
  thehive4py/endpoints/case_template.py
  thehive4py/types/case_template.py
Labels: category:enhancement, 2.x, changelog:added
